services:
   js-app:
      build:
         context: .
      container_name: js-app
      restart: unless-stopped
      init: true
      ports:
         - '8000:8000'
      environment:
         - MONGO_URI=mongodb://mongo:27017/mydatabase
      depends_on:
         - mongo
      networks:
         - backend

   mongo:
      image: mongo:6.0
      container_name: mongo
      restart: unless-stopped
      volumes:
         - mongo-data:/data/db
      ports:
         - '27017:27017'
      networks:
         - backend

   mongo-express:
      image: mongo-express:1.0.0
      container_name: mongo-express
      restart: unless-stopped
      ports:
         - '8081:8081'
      environment:
         - ME_CONFIG_MONGODB_SERVER=mongo
         - ME_CONFIG_MONGODB_PORT=27017
         - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
         - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
         - ME_CONFIG_BASICAUTH_USERNAME=admin
         - ME_CONFIG_BASICAUTH_PASSWORD=pass
      depends_on:
         - mongo
      networks:
         - backend

volumes:
   mongo-data:

networks:
   backend:
      driver: bridge
